# Generated by Django 5.1.7 on 2025-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('No derechohabiente', 'No derechohabiente'), ('Privado', 'Privado')], max_length=50)),
                ('problema', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
